UMAprotocol/umaverse

next.config.js
package.json
sentry.client.config.js
sentry.server.config.js
utils/errors.ts
utils/umaApi.ts
yarn.lock

**Motivation**
This PR adds error reporting with https://sentry.io . It will report all unhandled exceptions, synth fetching exceptions and some performance.  
**Details**
Sentry is really smart and will detect perf and unhandled errors by itself, however, it was necessary to add an explicit report for when a synth fails to fetch as that is done in a `map` and we don't want to interrupt the mapping if only one synth fails.
**Testing**
Signed-off-by: Gamaranto <francesco@umaproject.org>

feat(umaverse): add error reporting 

---

components/Placeholder.tsx
components/index.ts
package.json
pages/[address].tsx
pages/_app.tsx
pages/index.tsx
utils/contentful.ts
utils/umaApi.ts
yarn.lock

**Motivation**
This PR moves umaverse from being all SSR  (server side rendering) to using ISR (incremental static regeneration) to increase speed.
**Details** 
The fundamental difference between the two approaches is that how data is kept fresh and served. With SSR, all data is fetched and used to generate the page _at request time_ , while with ISR data is fetched _at build time_ and pages can be served immediately after a user request, to keep this data fresh, it is refetched client-side and kept up to date with React Query. 
To set up this process, some boilerplate is necessary and since the code can look obscure, here are some useful resources about the whole setup process:
- https://nextjs.org/docs/basic-features/data-fetching
- …

feat(umaverse): move to ISR

---

components/lsp-form/Collateral.tsx
components/lsp-form/LSPForm.tsx
components/lsp-form/LongShort.tsx
components/lsp-form/MintForm.tsx
components/lsp-form/RedeemForm.tsx
components/lsp-form/helpers.ts
components/text-input/TextInput.tsx
pages/testing.tsx

**Motivation**
Be able to redeem functions from LSP range contract
**Summary**
1) Connected redeem form to contract.
2)  Added keydown function to prevent non-numeric characters, outside of a couple specific ones.
**Testing**

feat: Redeem tokens from contract

---

components/EmpHero.tsx
components/Information.tsx
components/LspHero.tsx
components/SynthPlaceholderIcon.tsx
components/Table.tsx
components/Value.tsx
components/index.ts
pages/[address].tsx
pages/index.tsx
utils/constants.ts
utils/contentful.ts
utils/umaApi.ts

**Motivation**
This PR integrates the new API calls with umaverse UI. It does not however, merge the testing page into the address page 
**Details**
The API client has been refactored to accomodate for the new API, the `[address]` page now can distinguish between LSPs and EMPs and will render different views based on that.
**Testing**

Integrate with api

---

utils/umaApi.ts

Previous merge resulted in a few missing types. These were added back here.

fix: type error on merge

---

pages/index.tsx

**Motivation**
This PR fixes a minor bug making the TVM call error and thus not providing fresh values for global tvm
**Testing**

fix(umaverse): remove curated address for tvm

---

components/Hero.tsx
utils/umaApi.ts

The previous fix for merge issues simply added back previously removed types that were required for text search.
This PR re-removes those types and uses the updated types. It also makes a few small changes to the text search to make it compatible with LSPs and correctly display their names.

fix: more complete fix for type issues and text search

---

components/Information.tsx

Very minor formatting improvements.
The raw price value returned by the price id should be divided by 1e18.
The min tokens needs to be divided by the 1e[token_decimals], not necessarily 1e18.
Note: it may also make sense to have a standard way of formatting decimals because a lot of them go out to many more sig-figs than necessary because of the high-precision in solidity. We may want to have a standard way to deal with this, but that seemed more involved and opinionated, so I wanted to leave it to those with more expertise.
Before:
After:

fix(token-information): minor formatting improvements for price and min tokens

---

pages/[address].tsx

[address].tsx view did not query relevant data needed. It does now.

bug: search bar works in [address] view.

---

components/lsp/MintForm.tsx

**Motivation**
UI should split approve and mint transactions.
**Details**
**Testing**

feat: Split approve and mint, show in UI

---

components/Table.tsx
hooks/index.ts
hooks/useCachedState.tsx

**Motivation**
This PR adds persistence for Table filters as requested by: https://app.clubhouse.io/uma-project/story/1961/when-a-user-filters-and-selects-a-token-and-then-clicks-back-the-filter-they-previously-selected-should-still-be-displayed
**Details**
I've added a hook called `useCachedState` which takes care of persisting state between mount/unmount of components with the same "key" , in this specific use case, I've used it with key "table" 
**Testing**

feat(umaverse): add persistence to table filters

---

components/Information.tsx
pages/[address].tsx

**Motivation**
This PR collapses the grid into 2 columns instead of 4
Before:
After:
https://app.clubhouse.io/uma-project/story/1929/rework-the-grid-for-the-lsp-page
**Details**
To make this change without introducing a lot of complexity or changing the markup dynamically, I've changed the order of components of the grid on mobile. 
**Testing**

feat(umaverse): change grid structure

---

components/lsp/LSP.tsx
pages/[address].tsx

**Motivation**
https://app.shortcut.com/uma-project/story/2002/incorrect-wallet-balances-are-shown-in-the-minting-module-in-certain-scenarios
**Summary**
Balance were incorrect when moving between address pages
Changed reference to erc20 contract, and cleaned up minor issues seen in LSP / [address].
**Testing**

Bug: Incorrect balances

---

components/Table.tsx

TVL percent can sometimes be null. Show a "-" if it is.
https://app.shortcut.com/uma-project/story/2413/fix-minor-glitch-for-contracts-with-no-funding-for-a-couple-of-seconds-umaverse-shows-null-in-the-24h-change-field-afterwards

fixed null percent.

---

components/lsp/LSP.tsx

Note; this change wouldn't make sense under normal circumstances, but the expected contractState data coming from the API seems to be undefined in at least some cases, so this routes around that issue for the settlement use case.

fix: remove state guard to allow settle to be tested even if the contractState isn't expired

---

components/lsp/LSP.tsx
components/lsp/MintForm.tsx
hooks/useERC20ContractValues.ts
pages/[address].tsx

Motivation:
https://app.shortcut.com/uma-project/story/3539/unable-to-approve-certain-amounts-on-umaverse
User has limited approval, but app does not recognize it when minting
Fix:
We were comparing approvals against the users wallet balance rather than the amount set in the input field. This changes it so approvals are checked vs user input.
Tests:
Tested on mainnet manually

fix: fix approvals to check against amount input

---

components/lsp/LSP.tsx
components/lsp/LSPForm.tsx
utils/umaApi.ts

Motivation
https://app.shortcut.com/uma-project/story/3744/eliminate-use-of-contract-state-variable-in-umaverse
Summary
Adds an additional check to see if we can expire then settle the contract. This lets us know what state the contract is in. No longer need to rely on api or previous abis for this particular variable.
Screens
Testing
Tested using the hardhat testing scripts

fix: determine on chain contract state

---

pages/[address].tsx
pages/index.tsx
utils/chainId.ts
utils/contentful.ts
utils/index.ts
utils/umaApi.ts
yarn.lock

**Motivation**
This PR refactors the API Client and the Contentful client to accept chain Id as parameter.
**Details** 
The changes to the Contentful client are minimal, an additional `getSynthsByChain` has been added.
In the API client some things have changed:
- There is now a function called `constructClient` which will take in a ChainId and give back a `Client` object. This fn is memoized for performance, so it won't reinstantiate an existing client if called twice.
- `fetchCompleteSynths` has been moved inside the client
- a `fetchGlobalTvm` function has been added to fetch TVM across all clients. The function is imperfect, as it should not fetch from the same URL twice, and it should filter out errors instead of failing completely. It requires more work but I didn't want to block …

feat(umaverse): refactor api client to use chain id

---

components/LspHero.tsx

This PR fixes a bug that was causing the LSP token balances banner to be shown even if the user's wallet was not connected

fix: hide balances if wallet isn't connected

---

components/Table.tsx
pages/index.tsx

Story details: https://app.shortcut.com/uma-project/story/444
Icons centered in of row in rable
Adjust margin of text and copy.
7

fix: Remove TVM from UMAverse and adjust boxes

---

components/EmpHero.tsx
components/Table.tsx
pages/[chain]/[address].tsx
utils/format.ts
utils/umaApi.ts

Make FE more resilient in case API's tvl field is missing for contracts

fix: prevent parse to eth error

---

components/lsp/RedeemForm.tsx

Take in consideration the number of decimals for computing the wei amount to be redeemed
I tested the redeem functionality on a local fork of the mainnet.

fix: consider decimals for calculating redeemed amount

---

utils/contentful.ts
utils/umaApi.ts

Issue: Related contracts don't appear on the bottom of the contract page
This is just a one line fix, but took me a while to figure out what the problem was. ["this" execution context](https://github.com/UMAprotocol/umaverse/blob/master/utils/umaApi.ts#L113) was `undefined` inside `fetchCompleteSynth` method. This is some JS specific behaviour, but most probably when `map` calls the callback function, it causes the `fetchCompleteSynth` method to lose its initial execution context. I refactored the Client's methods to arrow functions

fix: call api client method explicitly inside map cb

---

utils/defillama.ts

Signed-off-by: Alex Gaines <againes@umaproject.org>
Defillama is updating our adapter to represent the total value secured (TVS) which has caused the TVL endpoint to decrease by over 50%. We are waiting for them to include an oracle endpoint that we can update to use. It should be ready soon, however, I think we should update to include the other projects TVL until it is ready.
The below update is resource intensive but I tried to make as few code changes as possible and should be changed back soon to the current version except for using a different endpoint (TVS instead of TVL).

Temporary update due to defillama change

---

components/lsp/MintForm.tsx
components/lsp/RedeemForm.tsx

Reset LSP form inputs only after tx is confirmed
[Issue here](https://app.shortcut.com/uma-project/story/4578/when-redeeming-i-enter-in-a-value-to-redeem-and-submit-a-tx-but-once-i-click-redeem-the-input-values-i-entered-are-cleared)

fix: reset form inputs after tx is confirmed

---

pages/[chain]/[address].tsx
utils/umaApi.ts

The current production app crashes if the API url of the contract's chain is not declared

fix: prevent crash if api url doesn't exist

---

components/LineChart.tsx
components/LspHero.tsx
components/lsp/MintForm.tsx
components/lsp/RedeemForm.tsx
pages/[chain]/[address].tsx
utils/constants.ts

This lets us delay refetches after a transaction by adjusting confirmation times. They were hardcoded to 1 before, but we might want to increase that as sometimes fetching balances are not updated immediately after tx. For testing i've disabled the change chain dialogs only when on a testnet chain id.

fix: allow configurable confirmations and testnet

---

pages/[chain]/[address].tsx

Signed-off-by: amateima <amatei@umaproject.org>
The LSP form needs to be hidden if contract is expired and wallet not connected

fix: hide lsp form for expired contracts and wallet not connected

---

components/lsp/LSP.styled.tsx
components/lsp/LSPForm.tsx
components/lsp/MintForm.tsx
components/lsp/RedeemForm.tsx
pages/[chain]/[address].tsx

Previously settle button was clickable when disabled, triggering a metamask transaction when clicked.  This is because rather than using the `disabled` prop, we used `showDisabled` which does not actually disable button events. 
This also happened to affect the mint button, so this change also fixes that button

fix: settle no longer clickable when disabled

---

components/Information.tsx
pages/[chain]/[address].tsx
pages/index.tsx

this just use pairName for the title and "name" fields in the details page. 
before
after

fix: use pairName instead of longTokenName on lsp details

---

components/Information.tsx

Signed-off-by: amateima <amatei@umaproject.org>
This PR improves the UI of the Token Information table by showing the address on a single line and by aligning the Copy address button to be centered vertically

fix: fix token info table

---

utils/defillama.ts

Signed-off-by: Alex Gaines <againes@umaproject.org>
This PR fixes a current issue (defillama name change from UMA to Outcome) causing TVL to be shown as 0 and also updates TVL to use the defillama oracle endpoint. This will prevent the current issue from happening in the future and reduces maintenance.

fix: update global TVL endpoint

---

utils/defillama.ts

We were showing the change in tvl from today to yesterday rather than yesterday to today. there was also a bug with selecting timestamps to sort

fix: 24 hour total tvl

---

components/Table.tsx

closes #UMA-2144
Columns removed from table:
- Rank
- TVL
- 24hr change

remove rank & stats columns
