UMAprotocol/umaverse

- components/Information.tsx
- components/Table.tsx
- pages/404.tsx
- pages/[address].tsx
- pages/_app.tsx
- pages/index.tsx
- utils/constants.ts
- utils/umaApi.ts
**Motivation**
This PR adds some minor fixes as in the feedback doc and the comments in the v1 PR that were left unaddressed.
**Testing**
Signed-off-by: Gamaranto <francesco@umaproject.org>
> fix(umaverse): minor fixes

- components/LineChart.tsx
- components/Table.tsx
Signed-off-by: Gamaranto <francesco@umaproject.org>
> fix(umaverse): remove line-clamp

- components/dropdown/Dropdown.styled.tsx
- components/lsp-form/Collateral.tsx
- components/lsp-form/LSPForm.styled.tsx
- components/lsp-form/LSPForm.tsx
- components/lsp-form/LongShort.tsx
- components/lsp-form/MintForm.tsx
- components/lsp-form/RedeemForm.tsx
- components/lsp-form/createERC20ContractInstance.ts
- components/lsp-form/createLSPContractInstance.ts
- components/lsp-form/useTokensCreatedEvents.ts
- components/tabs/Tabs.styled.tsx
- components/text-input/TextInput.tsx
- hooks/useERC20ContractValues.ts
- hooks/usePrevious.ts
- package.json
- pages/testing.tsx
- utils/constants.ts
- utils/convertFromWeiSafely.ts
- utils/convertToWeiSafely.ts
- yarn.lock
**Motivation**
Mint functionality works on contract.
**Summary**
Note: In order to get this working, you must spin up a fork of mainnet and set up the hardhat fork in metamask.
**Details**
**Testing**
> feat: add mint functionality for LSP

- README.md
- hooks/index.ts
- hooks/useConnection.tsx
- hooks/useOnboard.tsx
- package.json
- pages/_app.tsx
- utils/chainId.ts
- utils/constants.ts
- yarn.lock
**Motivation**
This PR adds the useConnection hook to umaverse, it does not touch the logic for injecting the test provider as I wasn't unsure how that is used exactly. 
**Testing**
> feat(umaverse): Connect wallet

- components/lsp-form/LSPForm.styled.tsx
- components/lsp-form/LSPForm.tsx
- pages/testing.tsx
**Motivation**
UI should expire and settle the contract and allow users to redeem remaining balances of their long and short tokens. 
**Details**
Note: Testing the flow is rather complicated, involving using a bunch of scripts in hardhat-test, setting up MM with your hardhat instance, and using hte UI.
**Testing**
> Feat: LSP flow works

- components/Dot.tsx
- components/LspHero.tsx
- components/lsp-form/LSPForm.tsx
- components/lsp-form/MintForm.tsx
- hooks/useERC20ContractValues.ts
- pages/index.tsx
- pages/testing.tsx
- public/icons/wallet.svg
**Motivation**
Adds onboard integration and wallet UI to LSP pages.
**Details**
One LSP page is `localhost/0x4625c7049636Da335Df0f812ECFc8B0e3268D6F3`. You can check the CMS for more LSPs 
**Testing**
> feat(umaverse): add wallet ui and onboard integration

- components/Table.tsx
- pages/[address].tsx
- pages/index.tsx
- utils/errors.ts
- utils/umaApi.ts
**Motivation**
This PR updates API calls (will work once is merged https://github.com/UMAprotocol/protocol/pull/3288#event-5130891451) and fixes filtering on the main table.
**Details**
This PR is expected to be broken until this PR https://github.com/UMAprotocol/protocol/pull/3288 is merged and the new version of the API is deployed 
**Testing**
> fix(umaverse): fix filtering and update API calls

- components/Information.tsx
- components/Layout.tsx
- components/lsp/LSP.tsx
- components/lsp/LSPForm.styled.tsx
- components/lsp/LSPForm.tsx
- pages/[address].tsx
- utils/umaApi.ts
Responsive Css fixes
https://app.clubhouse.io/uma-project/story/1926/make-sure-1-1-release-works-on-various-devices-ipad-mobile-various-computer-screens-etc
Update box shadow
https://app.clubhouse.io/uma-project/story/1936/update-shadow-to-match-figma-design-on-modules
Boolean added for this state as it's complicated:
https://app.clubhouse.io/uma-project/story/1893/settle-button-should-be-disabled-in-this-state-in-the-image
>  feat: Responsive css, drop shadow fix, settle button disabled fix

- components/lsp/MintForm.tsx
- components/lsp/RedeemForm.tsx
- components/lsp/helpers.ts
- components/text-input/TextInput.tsx
**Motivation**
Certain string values caused app to crash
**Summary**
Capture the error and show an invalid string error when the user adds too many decimals or shows a single decimal with no number.
**Testing**
> bug: Decimals crash bug

- components/lsp/LSP.tsx
- components/lsp/LSPForm.tsx
- components/lsp/MintForm.tsx
- components/lsp/RedeemForm.tsx
- next-env.d.ts
> hotfix-debug

- next-env.d.ts
- pages/[address].tsx
- utils/contentful.ts
**Motivation**
This PR expands the recommend list in the "You might also like" section: https://app.clubhouse.io/uma-project/story/1955/update-you-might-be-interested-section-to-always-recommend-another-related-product-if-no-other-related-product-recommend
**Testing**
> feat(umaverse): expand recommended synths

- components/About.tsx
- components/SynthPlaceholderIcon.tsx
- next-env.d.ts
- next.config.js
- package.json
- yarn.lock
**Motivation**
This PR adds support for better markdown formatting and also updates Umaverse to use webpack 5, the update is needed for using remark plugins and improves build speed overall. 
https://app.clubhouse.io/uma-project/story/1896/data-not-formatting-correctly-from-cms
**Details**
For some next and remark limitations, plugins have to imported dynamically once the component has mounted.
**Testing**
> feat(umaverse): improve markdown support

- components/lsp/MintForm.tsx
user should be able to approve without filling out any input.
> move approval logic amount of amount input check.

- components/Footer.tsx
Removed risk labs as requested.
> removed risk labs 2020

- package.json
- pages/index.tsx
- utils/defillama.ts
Signed-off-by: Alex Gaines <againes@umaproject.org>
**Motivation**
This PR changes the global TVL and percent change to use defillama. The goal is to be consistent with our TVL calc for umaverse, UMA's website, and defillama.
**Testing**
> Update to use defillama for tvl

- next.config.js
- pages/[chain]/[address].tsx
- utils/chainId.ts
- utils/contentful.ts
- utils/index.ts
This PR adds nested routing based on chain and also adds next redirects to redirect from  /0x... to /ethereum/0x... for backwards compatibility
> feat(umaverse): add multichain routing

- pages/index.tsx
- yarn.lock
> feat: removed tvm; adjusted card size

- components/Table.tsx
> fix: add chainName to url

- components/header/Header.tsx
Changes link to umaproject.org
> feat: uma header links to umaproject.org

- utils/constants.ts
> feat: make coinbase preferred

- components/LspHero.tsx
- components/lsp/ConnectWallet.tsx
- components/lsp/LSPForm.tsx
- components/lsp/MintForm.tsx
- components/lsp/RedeemForm.tsx
- hooks/useOnboard.tsx
- package.json
- utils/chainId.ts
- utils/constants.ts
- yarn.lock
https://app.shortcut.com/uma-project/story/4689/unable-to-connect-my-wallet-on-umaverse
Fixed strange MM connect issue. When click `Connect`, Metamask didn't popup if locked and connected to other chain than mainnet
> fix: unable to connect locked MM wallet 

- components/LspHero.tsx
This is an insignificant change. Just need an approval to merge it
> fix: change wallet banner text

- components/Hero.tsx
Signed-off-by: amateima <amatei@umaproject.org>
The routing for the searched contracts is broken. This PR adds the chain name as part of the route
> fix: add chain name to the contract route

- components/About.tsx
- components/Table.tsx
- components/dropdown/Dropdown.tsx
- components/header/NavLinks.tsx
- components/lsp/Collateral.tsx
- components/lsp/LSP.tsx
- components/lsp/LSPForm.tsx
- components/lsp/LongShort.tsx
- components/lsp/MintForm.tsx
- components/lsp/RedeemForm.tsx
- components/lsp/SwitchWalletLsp.tsx
- components/lsp/createERC20ContractInstance.ts
- components/lsp/createLSPContractInstance.ts
- components/lsp/helpers.ts
This is not supposed to affect any functionality, its simply fixing warning produced by tslint
> improve: remove warnings where possible

- vercel.json
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
> Fix headers

- components/Icons.tsx
- components/lsp/LSPForm.tsx
- components/lsp/WalletConnectBanner.tsx
- pages/[chain]/[address].tsx
> feat: banner showing instructions for alternative method

- components/Table.tsx
- components/banners/AnalyticsBanner.tsx
- components/banners/BannerWrapper.tsx
- components/banners/index.ts
> feat: add banner directing user to dune dashboard

- components/Icons.tsx
- components/header/Header.tsx
- components/lsp/LSPForm.tsx
- components/lsp/WalletConnectBanner.tsx
- pages/[chain]/[address].tsx
- utils/constants.ts
> fix: disable wallet connect from projects.uma.xyz
